package nz.ac.wgtn.shadedetector;

public enum ProcessingStage {
    QUERY_RESULTS,
    CONSOLIDATED_QUERY_RESULTS,
    VALID_POM,
    NO_DEPENDENCY_TO_VULNERABLE,
    CLONE_DETECTED,
    POV_INSTANCE_COMPILED,
    POV_INSTANCE_VULNERABILITY_CONFIRMED,
    POV_INSTANCE_VULNERABILITY_CONFIRMED_SHADED
}
